#!/usr/bin/env node

import fs from 'fs';
import path from 'path';

// Change directory to 'dist'
process.chdir('dist');

// Read and parse the manifest file
const manifestPath = path.join('.vite', 'manifest.json');
const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf-8'));

// Read the 'index.html' file
let indexHtml = fs.readFileSync('index.html', 'utf-8');

// List of files to process
const files = [
    { dst: 'assets/logo.svg', src: manifest['assets/logo.svg'].file },
    { dst: 'assets/index.css', src: manifest['index.html'].css[0] },
    { dst: 'assets/bundle_v2.js', src: manifest['index.html'].file }
];

// Replace and rename files
files.forEach(({ dst, src }) => {
    console.log(`Renaming ${src} to ${dst}`);
    indexHtml = indexHtml.replace(`/${src}`, dst);
    try {
        fs.renameSync(src, dst);
    } catch (e) {
        console.error(`Failed to rename ${src} to ${dst}:`, e);
    }
});

// Write the updated 'index.html'
fs.writeFileSync('index.html', indexHtml, 'utf-8');
